---
- name: Add Nodesource Keys
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add Node 12 deb
  become: yes
  apt_repository:
    repo: deb https://deb.nodesource.com/node_12.x bionic main
    state: present
    filename: node-12
    update_cache: yes

- name: Add Node 12 deb-src
  become: yes
  apt_repository:
    repo: deb-src https://deb.nodesource.com/node_12.x bionic main
    state: present
    filename: node-12-src
    update_cache: yes

- name: Add Yarn deb
  become: yes
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
    filename: yarn-deb
    update_cache: yes
